import { ACCEPTED_FILE_EXTENSIONS } from '../constants';
import { readImageMetadata } from './imageMetadata';
import { slugify } from './slugify';

import type { AnimalItem, FileExportGroups, ManagedFile, PromptItem } from '../types';

export const getExpectedFilename = (animalName: string): string => `${slugify(animalName)}.png`;

export const isImageFile = (file: File | ManagedFile): boolean => {
  const name = 'name' in file ? file.name : '';
  const type = 'type' in file ? file.type : '';
  return type.startsWith('image/') || /\.(png|jpe?g|webp)$/i.test(name);
};

export const isAcceptedFile = (file: File): boolean => {
  const extension = file.name.split('.').pop()?.toLowerCase() ?? '';
  return ACCEPTED_FILE_EXTENSIONS.includes(extension);
};

export const formatBytes = (bytes: number): string => {
  if (bytes === 0) {
    return '0 B';
  }

  const units = ['B', 'KB', 'MB', 'GB'];
  const unitIndex = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / 1024 ** unitIndex;

  return `${value.toFixed(value >= 10 || unitIndex === 0 ? 0 : 1)} ${units[unitIndex] ?? 'B'}`;
};

export const fileToDataUrl = async (file: File | Blob): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result);
        return;
      }

      reject(new Error('Could not read file data as a data URL'));
    };
    reader.onerror = () => reject(new Error('Could not read file data'));
    reader.readAsDataURL(file);
  });

export const fileToText = async (file: File | Blob): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result);
        return;
      }

      reject(new Error('Could not read file as text'));
    };
    reader.onerror = () => reject(new Error('Could not read text file'));
    reader.readAsText(file);
  });

export const downloadBlob = (blob: Blob, fileName: string): void => {
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = fileName;
  document.body.append(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(objectUrl);
};

export const createGeneratedFile = (
  blob: Blob,
  name: string,
  kind: ManagedFile['kind'],
  imageMetadata?: ManagedFile['imageMetadata'],
): ManagedFile => {
  const now = new Date().toISOString();
  const file = new File([blob], name, { type: blob.type || 'application/octet-stream' });
  const objectUrl = imageMetadata ? URL.createObjectURL(file) : undefined;

  return {
    id: crypto.randomUUID(),
    file,
    name,
    originalName: name,
    size: file.size,
    type: file.type,
    addedAt: now,
    kind,
    ...(objectUrl ? { objectUrl } : {}),
    ...(imageMetadata ? { imageMetadata } : {}),
    reviewState: 'approved',
    reviewNotes: 'Generated by app.',
    explicitlyConfirmed: true,
  };
};

export const createManagedFile = async (
  file: File,
  animals: AnimalItem[],
): Promise<ManagedFile> => {
  const now = new Date().toISOString();
  const imageMetadata = isImageFile(file) ? await readImageMetadata(file) : undefined;
  const matchingAnimal = animals.find(
    (animal) => getExpectedFilename(animal.name).toLowerCase() === file.name.toLowerCase(),
  );
  const objectUrl = isImageFile(file) ? URL.createObjectURL(file) : undefined;

  return {
    id: crypto.randomUUID(),
    file,
    name: file.name,
    originalName: file.name,
    size: file.size,
    type: file.type || 'application/octet-stream',
    addedAt: now,
    kind: 'uploaded',
    ...(objectUrl ? { objectUrl } : {}),
    ...(imageMetadata ? { imageMetadata } : {}),
    reviewState: 'pending',
    reviewNotes: '',
    ...(matchingAnimal ? { mappedAnimalId: matchingAnimal.id } : {}),
    explicitlyConfirmed: false,
  };
};

export const dedupeIncomingFiles = (
  existingFiles: ManagedFile[],
  incomingFiles: File[],
): { accepted: File[]; duplicates: string[]; unsupported: string[] } => {
  const existingNames = new Set(existingFiles.map((file) => file.name.toLowerCase()));
  const accepted: File[] = [];
  const duplicates: string[] = [];
  const unsupported: string[] = [];

  incomingFiles.forEach((file) => {
    const normalizedName = file.name.toLowerCase();

    if (!isAcceptedFile(file)) {
      unsupported.push(file.name);
      return;
    }

    if (existingNames.has(normalizedName)) {
      duplicates.push(file.name);
      return;
    }

    existingNames.add(normalizedName);
    accepted.push(file);
  });

  return { accepted, duplicates, unsupported };
};

export const createPromptItems = (animals: AnimalItem[]): PromptItem[] =>
  animals.map((animal) => ({
    animalId: animal.id,
    animalName: animal.name,
    expectedFilename: getExpectedFilename(animal.name),
    prompt: `Front-facing realistic ${animal.name.toLowerCase()} face paper mask for children, friendly expression, symmetrical face, centered composition, transparent background, printable craft asset, high resolution, clear human eye holes, no text, no watermark, no background, original artwork.`,
    negativeRequirements:
      'no copyrighted character, no brand, no celebrity, no text, no watermark, no scary expression, no full body, no background, no distorted face',
  }));

export const getFileForAnimal = (
  files: ManagedFile[],
  animalId: string,
  state: ManagedFile['reviewState'] = 'approved',
): ManagedFile | undefined =>
  files.find(
    (file) =>
      file.kind === 'uploaded' &&
      isImageFile(file) &&
      file.mappedAnimalId === animalId &&
      file.reviewState === state,
  );

export const groupFilesForExport = (
  files: ManagedFile[],
  animals: AnimalItem[],
): FileExportGroups => {
  const validAnimalIds = new Set(animals.map((animal) => animal.id));
  const usedAnimalIds = new Set<string>();

  const approvedMapped = files.filter((file) => {
    if (
      file.kind !== 'uploaded' ||
      !isImageFile(file) ||
      file.reviewState !== 'approved' ||
      !file.mappedAnimalId ||
      !validAnimalIds.has(file.mappedAnimalId) ||
      usedAnimalIds.has(file.mappedAnimalId)
    ) {
      return false;
    }

    usedAnimalIds.add(file.mappedAnimalId);
    return true;
  });

  const approvedIds = new Set(approvedMapped.map((file) => file.id));
  const rejected = files.filter(
    (file) => file.kind === 'uploaded' && isImageFile(file) && file.reviewState === 'rejected',
  );
  const rejectedIds = new Set(rejected.map((file) => file.id));
  const unused = files.filter(
    (file) => file.kind === 'uploaded' && !approvedIds.has(file.id) && !rejectedIds.has(file.id),
  );

  return {
    approvedMapped,
    rejected,
    unused,
  };
};

export const getSourceFiles = (files: ManagedFile[]): ManagedFile[] =>
  files.filter((file) => file.kind === 'uploaded');

export const replaceGeneratedFiles = (
  files: ManagedFile[],
  generatedFiles: ManagedFile[],
  kind: Extract<ManagedFile['kind'], 'generated-pdf' | 'generated-preview'>,
): ManagedFile[] => [...files.filter((file) => file.kind !== kind), ...generatedFiles];

export const createPngBlobFromImage = async (file: File): Promise<Blob> => {
  const dataUrl = await fileToDataUrl(file);
  const image = await new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Could not normalize image ${file.name}`));
    img.src = dataUrl;
  });

  const canvas = document.createElement('canvas');
  canvas.width = image.naturalWidth;
  canvas.height = image.naturalHeight;
  const context = canvas.getContext('2d');

  if (!context) {
    throw new Error('Canvas is unavailable');
  }

  context.drawImage(image, 0, 0);

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (!blob) {
        reject(new Error(`Could not create PNG for ${file.name}`));
        return;
      }

      resolve(blob);
    }, 'image/png');
  });
};
